# Change these first
owner: itishermann # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: 10k-steps
    url: https://10k-steps.itishermann.me
  - name: Dokploy
    url: https://dokploy.itishermann.me
#    Disabled because Hashnode doesn't allow to ping the server
#  - name: Blog
#    url: https://itishermann.me
  - name: InvoiceNinja
    url: https://invoiceninja.itishermann.me
  - name: Log To
    url: https://auth.itishermann.me
  - name: Log to admin
    url: https://logto.itishermann.me
  - name: Mediation Immobilière
    url: https://mediation-immobiliere.com
  - name: Play Pulse (Client)
    url: https://play-pulse.itishermann.me
#    Disabled because of the server being shut down when not used
#  - name: Play Pulse (Server)
#    url: https://play-pulse-server.itishermann.me/actuator/health
  - name: Turbo cache
    url: https://turbo.itishermann.me
  - name: Kaptaain (client)
    url: https://app.kaptaain.com/api/health
  - name: Kaptaain (server)
    url: https://api.kaptaain.com/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.itishermann.me
  # baseUrl: /your-repo-name
  logoUrl: https://static.itishermann.me/images/logo/white.svg
  theme: night
  name: Uptime Monitor - itishermann
  introTitle: itishermann's Uptime Monitor
  introMessage: "The status of my websites and services is monitored here. If there are any interruptions, a note will be posted here."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Blog
      href: https://itishermann.me
    - title: LinkedIn
      href: https://www.linkedin.com/in/itishermann/
    - title: Resume
      href: https://itishermann.me/resume

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
